const STAGES = ['转写语音', '提取 16 项基础字段', '核对「下一步」是否含时间与目标'];
const SOURCES = [{ key: 1, title: '9 月 12 日拜访记录', description: '「已获得 CIO 支持，预算在四季度审批」', url: '/pages/visit/detail?id=1' }, { key: 2, title: '客户档案 · 潜力', description: '预算 320 万，台数 1200', url: '/pages/customer/detail?id=1' }];
const MAP_POINTS = [
  { id: 1, name: '华宸数据科技', potential: 8, relationship: 9, tone: 'good', amountBand: 'large' },
  { id: 2, name: '北辰智造集团', potential: 7, relationship: 3, tone: 'watch', amountBand: 'medium' },
  { id: 3, name: '云岭物流', potential: 8.5, relationship: 2, tone: 'bad', amountBand: 'medium' },
  { id: 4, name: '瀚海医疗', potential: 3, relationship: 8, tone: 'good', amountBand: 'small' },
  { id: 5, name: '恒远建材', potential: 2, relationship: 2, tone: 'pending', amountBand: 'small' },
  { id: 6, name: '恒远建材（华南）', potential: 2.2, relationship: 2.3, tone: 'pending', amountBand: 'small' },
  { id: 7, name: '星河教育', potential: 6, relationship: 6.5, tone: 'watch', amountBand: 'large' },
];
Page({
  data: {
    summaryMetrics: [{ label: '未完成', value: 18 }, { label: '已完成', value: 4 }, { label: '全部任务', value: 22 }],
    summaryTags: [{ label: '主攻区' }, { label: 'Tier-1' }, { label: '需关注', tone: 'watch' }],
    descRows: [{ label: '任务类别', value: '客户任务' }, { label: '关联商机', value: '知识助理项目', tappable: true }, { label: '截止时间', value: '2026年9月23日 09:00', tone: 'danger' }, { label: '合作伙伴', value: '' }, { label: '客户来源', value: null, required: true }],
    descGrid: [{ label: '客户类型', value: '商机客户' }, { label: '客户名称', value: '星河智能制造（广州）有限公司' }, { label: '拜访方式', value: '线上会议' }, { label: '拜访时长', value: '45 分钟' }, { label: '下一步', value: '整理试点清单，预约下一次方案沟通' }, { label: '首次拜访', value: '否' }],
    descShort: [{ label: '智能质检试点', value: '128 万 · 方案沟通' }, { label: '知识助理项目', value: '48 万 · 商机确认' }],

    filter: ['risk'], filterOpts: [{ value: 'risk', label: '有风险', count: 6 }, { value: 'main', label: '主攻区', count: 9 }, { value: 'asset', label: '客户资产', count: 7 }, { value: 'mine', label: '本人负责', count: 24 }],
    rows: [{ name: '华宸数据科技有限公司', summary: '客户资产 · 关系 8/10 · 地盘 HB-01', tone: 'good', reason: '近 30 天有高层拜访', time: '2 天前跟进' }, { name: '北辰智造集团', summary: '主攻区 · 关系 4/10', tone: 'watch', reason: '一周无跟进', time: '9 天前跟进' }],
    search: '', searchLoading: false,
    fieldName: '华宸数据科技', fieldNext: '', fieldBudget: '',
    sheet: false, sheetBusy: false, quarter: '第三季度',
    page: 2, moreLoading: false, moreEnd: false, shown: 40,
    sources: SOURCES, stages: STAGES, gen: 'running', genFail: 'failed', genFailStep: 0, barDisabled: false,
    quad: null, quadOpts: [{ value: 'attack', label: '主攻区', count: 9 }, { value: 'asset', label: '客户资产', count: 12 }, { value: 'spot', label: '见单打单', count: 3 }, { value: 'resource', label: '客户资源', count: 7 }],
    metrics: [{ label: '年度合同额 · 万元', value: 1880 }, { label: '确收 · 万元', value: 138 }, { label: '回款 · 万元', value: null, note: '财务还没登记' }, { label: '客户', value: 24, note: '比上季 +2 家' }], period: 'year', tab: 'todo',
    seg: 'map', segOpts: [{ value: 'map', label: '地图' }, { value: 'list', label: '列表' }, { value: 'table', label: '表格', disabled: true }],
    date: '', stage: 'verify', stageOpts: [{ value: 'find', label: '识别' }, { value: 'verify', label: '验证', count: 3 }, { value: 'plan', label: '方案' }, { value: 'sign', label: '签约', disabled: true }],
    amount: 320, summary: '已获得 CIO 支持，预算在四季度审批。',
    mapPoints: MAP_POINTS, mapZoom: '', mapSelected: null, chartState: 'error', tab5: 'home',
    ai: { value: '张总（CIO）', state: 'ai' }, aiLow: { value: '', state: 'ai' }, submitting: false,
    tlItems: [{ key: 1, time: '9 月 19 日 14:30', title: '拜访：见了 CIO 张总', description: '已获得 CIO 支持，预算在四季度审批', tone: 'good', actor: '王小明', tappable: true }, { key: 2, time: '9 月 15 日', title: '任务「补充客户预算」被拒绝', description: '对方意见：预算还没批，下周再填', tone: 'bad', actor: '李雷' }, { key: 3, time: '9 月 12 日', title: '一周无跟进，转为需关注', tone: 'watch' }, { key: 4, time: '9 月 8 日', title: '商机进入验证 30%', description: '数据中心扩容，预算 320 万', tone: 'neutral', actor: '王小明' }],
    files: [{ uid: 'f1', name: '拜访纪要.pdf', size: 245760, status: 'done', url: 'f1' }],
    filesBusy: [{ uid: 'b1', name: '合同扫描件.pdf', size: 1258291, status: 'uploading', url: 'b1' }, { uid: 'b2', name: '现场照片.jpg', size: 3145728, status: 'error', url: 'b2' }],
    resultMetrics: [{ label: '本周拜访', value: 6 }, { label: '待确认字段', value: 0 }, { label: '下一步', value: null, note: '10 月 8 日前发方案' }],
  },
  onTimeline(e) { wx.showToast({ title: `打开：${e.detail.item.title}`, icon: 'none' }); },
  onFiles(e) { this.setData({ files: e.detail.files }); },
  onResultPrimary() { wx.showToast({ title: '查看客户', icon: 'none' }); },
  onResultSecondary() { wx.showToast({ title: '再记一条', icon: 'none' }); },
  onSeg(e) { this.setData({ seg: e.detail.value }); },
  onDate(e) { this.setData({ date: e.detail.value }); },
  onStage(e) { this.setData({ stage: e.detail.value }); },
  onAmount(e) { this.setData({ amount: e.detail.value }); },
  onSummary(e) { this.setData({ summary: e.detail.value }); },
  onKpi(e) { wx.showToast({ title: `打开：${e.detail.label}`, icon: 'none' }); },
  onPoint(e) { this.setData({ mapSelected: e.detail.point.id }); wx.showToast({ title: e.detail.point.name, icon: 'none' }); },
  onCluster(e) { wx.showToast({ title: `重叠 ${e.detail.points.length} 家：${e.detail.points.map((p) => p.name).join('、')}`, icon: 'none' }); },
  onZoom(e) { this.setData({ mapZoom: e.detail.zoom }); },
  onUnrated() { wx.showToast({ title: '打开待评估列表', icon: 'none' }); },
  onMapEmpty() { wx.showToast({ title: '去客户列表', icon: 'none' }); },
  onChartRetry() { this.setData({ chartState: 'loading' }); setTimeout(() => this.setData({ chartState: 'error' }), 1200); },
  onTab5(e) { this.setData({ tab5: e.detail.value }); },
  onQuad(e) { this.setData({ quad: e.detail.value }); },
  onPeriod(e) { this.setData({ period: e.detail.value }); },
  onTab(e) { this.setData({ tab: e.detail.key }); },
  onFilter(e) { this.setData({ filter: e.detail.value }); },
  onSearch(e) { this.setData({ search: e.detail.value }); },
  onSearchSubmit() { this.setData({ searchLoading: true }); setTimeout(() => this.setData({ searchLoading: false }), 1200); },
  onSearchClear() { this.setData({ search: '' }); },
  onFieldName(e) { this.setData({ fieldName: e.detail.value }); },
  onFieldNext(e) { this.setData({ fieldNext: e.detail.value }); },
  onFieldBudget(e) { this.setData({ fieldBudget: e.detail.value }); },
  openSheet() { this.setData({ sheet: true }); },
  closeSheet() { this.setData({ sheet: false, sheetBusy: false }); },
  pickQuarter(e) { this.setData({ quarter: e.currentTarget.dataset.value }); },
  confirmSheet() { this.setData({ sheetBusy: true }); setTimeout(() => this.setData({ sheet: false, sheetBusy: false }), 800); },
  onPage(e) { this.setData({ page: e.detail.current }); },
  onMore() { this.setData({ moreLoading: true }); setTimeout(() => { const shown = Math.min(124, this.data.shown + 20); this.setData({ moreLoading: false, shown, moreEnd: shown >= 124 }); }, 800); },
  onSource(e) { wx.showToast({ title: `打开：${e.detail.item.title}`, icon: 'none' }); },
  onGenCancel() { this.setData({ gen: 'cancelled' }); },
  onGenRestart() { this.setData({ gen: 'running' }); },
  onGenFailRetry() { this.setData({ genFail: 'running', genFailStep: 1 }); setTimeout(() => this.setData({ genFail: 'done', genFailStep: 3 }), 900); setTimeout(() => this.setData({ genFail: 'failed', genFailStep: 0 }), 3000); },
  onBarToggle() { this.setData({ barDisabled: !this.data.barDisabled }); },
  onAi(e) { this.setData({ 'ai.value': e.detail.value, 'ai.state': e.detail.state }); },
  onAiConfirm() { this.setData({ 'ai.state': 'confirmed' }); },
  onAiRestore(e) { this.setData({ 'ai.value': e.detail.value, 'ai.state': 'ai' }); },
  onAiLow(e) { this.setData({ 'aiLow.value': e.detail.value, 'aiLow.state': e.detail.state }); },
  onSubmit() { this.setData({ submitting: true }); setTimeout(() => this.setData({ submitting: false }), 1500); },
});
