const STAGES = ['转写语音', '提取 16 项基础字段', '核对「下一步」是否含时间与目标'];
const SOURCES = [{ key: 1, title: '9 月 12 日拜访记录', description: '「已获得 CIO 支持，预算在四季度审批」', url: '/pages/visit/detail?id=1' }, { key: 2, title: '客户档案 · 潜力', description: '预算 320 万，台数 1200', url: '/pages/customer/detail?id=1' }];
Page({
  data: {
    filter: ['risk'], filterOpts: [{ value: 'risk', label: '有风险', count: 6 }, { value: 'main', label: '主攻区', count: 9 }, { value: 'asset', label: '客户资产', count: 7 }, { value: 'mine', label: '本人负责', count: 24 }],
    rows: [{ name: '华宸数据科技有限公司', summary: '客户资产 · 关系 8/10 · 地盘 HB-01', tone: 'good', reason: '近 30 天有高层拜访', time: '2 天前跟进' }, { name: '北辰智造集团', summary: '主攻区 · 关系 4/10', tone: 'watch', reason: '一周无跟进', time: '9 天前跟进' }],
    search: '', searchLoading: false,
    fieldName: '华宸数据科技', fieldNext: '', fieldBudget: '',
    sheet: false, sheetBusy: false, quarter: '第三季度',
    page: 2, moreLoading: false, moreEnd: false, shown: 40,
    sources: SOURCES, stages: STAGES, gen: 'running', genFail: 'failed', genFailStep: 0, barDisabled: false,
    quad: null, quadOpts: [{ value: 'attack', label: '主攻区', count: 9 }, { value: 'asset', label: '客户资产', count: 12 }, { value: 'spot', label: '见单打单', count: 3 }, { value: 'resource', label: '客户资源', count: 7 }],
    metrics: [{ label: '年度合同额 · 万元', value: 1880 }, { label: '确收 · 万元', value: 138 }, { label: '回款 · 万元', value: null, note: '财务还没登记' }, { label: '客户', value: 24, note: '比上季 +2 家' }], period: 'year', tab: 'todo',
    ai: { value: '张总（CIO）', state: 'ai' }, aiLow: { value: '', state: 'ai' }, submitting: false,
  },
  onQuad(e) { this.setData({ quad: e.detail.value }); },
  onPeriod(e) { this.setData({ period: e.detail.value }); },
  onTab(e) { this.setData({ tab: e.detail.key }); },
  onFilter(e) { this.setData({ filter: e.detail.value }); },
  onSearch(e) { this.setData({ search: e.detail.value }); },
  onSearchSubmit() { this.setData({ searchLoading: true }); setTimeout(() => this.setData({ searchLoading: false }), 1200); },
  onSearchClear() { this.setData({ search: '' }); },
  onFieldName(e) { this.setData({ fieldName: e.detail.value }); },
  onFieldNext(e) { this.setData({ fieldNext: e.detail.value }); },
  onFieldBudget(e) { this.setData({ fieldBudget: e.detail.value }); },
  openSheet() { this.setData({ sheet: true }); },
  closeSheet() { this.setData({ sheet: false, sheetBusy: false }); },
  pickQuarter(e) { this.setData({ quarter: e.currentTarget.dataset.value }); },
  confirmSheet() { this.setData({ sheetBusy: true }); setTimeout(() => this.setData({ sheet: false, sheetBusy: false }), 800); },
  onPage(e) { this.setData({ page: e.detail.current }); },
  onMore() { this.setData({ moreLoading: true }); setTimeout(() => { const shown = Math.min(124, this.data.shown + 20); this.setData({ moreLoading: false, shown, moreEnd: shown >= 124 }); }, 800); },
  onSource(e) { wx.showToast({ title: `打开：${e.detail.item.title}`, icon: 'none' }); },
  onGenCancel() { this.setData({ gen: 'cancelled' }); },
  onGenRestart() { this.setData({ gen: 'running' }); },
  onGenFailRetry() { this.setData({ genFail: 'running', genFailStep: 1 }); setTimeout(() => this.setData({ genFail: 'done', genFailStep: 3 }), 900); setTimeout(() => this.setData({ genFail: 'failed', genFailStep: 0 }), 3000); },
  onBarToggle() { this.setData({ barDisabled: !this.data.barDisabled }); },
  onAi(e) { this.setData({ 'ai.value': e.detail.value, 'ai.state': e.detail.state }); },
  onAiConfirm() { this.setData({ 'ai.state': 'confirmed' }); },
  onAiRestore(e) { this.setData({ 'ai.value': e.detail.value, 'ai.state': 'ai' }); },
  onAiLow(e) { this.setData({ 'aiLow.value': e.detail.value, 'aiLow.state': e.detail.state }); },
  onSubmit() { this.setData({ submitting: true }); setTimeout(() => this.setData({ submitting: false }), 1500); },
});
